# Screen dimensions
WIDTH = 600
HEIGHT = 600

# Board dimensions
ROWS = 8
COLS = 8
SQSIZE = WIDTH // COLS

BOARD_WIDTH = BOARD_HEIGHT = 512
MOVE_LOG_PANEL_WIDTH = 250
MOVE_LOG_PANEL_HEIGHT = BOARD_HEIGHT
DIMENSION = 8
SQUARE_SIZE = BOARD_HEIGHT // DIMENSION
MAX_FPS = 15
IMAGES = {}